plugins {
    id 'java'
    id 'application'
    id 'jacoco'
    id 'gg.jte.gradle' version '3.1.15'
    id 'org.springframework.boot' version '3.5.7'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'ru.mentee.power'
version = '1.0-SNAPSHOT'

ext {
    junitVersion = '5.11.0'
    assertjVersion = '4.0.0-M1'
    lombokVersion = '1.18.40'
    mockitoVersion = '5.14.2'
    servletVersion = '6.1.0'
    tomcatVersion = '11.0.1'
    jteVersion = '3.1.15'
    springBootVersion = '3.5.7'
    jteSpringBootVersion = '3.1.15'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    mainClass = 'ru.mentee.power.crm.Main'
}

repositories {
    mavenCentral()
}

configurations {
    mockitoAgent
}

dependencies {
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    testImplementation platform("org.junit:junit-bom:${junitVersion}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation "org.mockito:mockito-core:${mockitoVersion}"
    testImplementation "org.mockito:mockito-junit-jupiter:${mockitoVersion}"
    mockitoAgent "net.bytebuddy:byte-buddy-agent:1.15.4"

    implementation "jakarta.servlet:jakarta.servlet-api:${servletVersion}"
    implementation "org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}"

    implementation "gg.jte:jte:${jteVersion}"
    implementation "gg.jte:jte-runtime:${jteVersion}"
    implementation "gg.jte:jte-spring-boot-starter-3:${jteSpringBootVersion}"

    implementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

bootRun {
    mainClass = "ru.mentee.power.crm.spring.Application"
}

jte {
    sourceDirectory = file("src/main/jte").toPath()
    contentType = gg.jte.ContentType.Html
    binaryStaticContent = false
}

jacoco {
    toolVersion = '0.8.14'
}

test {
    useJUnitPlatform()
    jvmArgs += ["-javaagent:${configurations.mockitoAgent.singleFile}"]
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    classDirectories.setFrom(
            files(classDirectories.files.collect {
                fileTree(dir: it, exclude: [
                        '**/Main.class',
                        '**/Application.class'
                ])
            })
    )
    reports {
        xml.required = false
        csv.required = false
        html.required = true
        html.outputLocation = layout.buildDirectory.dir('reports/jacoco/test/html')
    }
}

jacocoTestCoverageVerification {
    dependsOn jacocoTestReport
    classDirectories.setFrom(
            files(classDirectories.files.collect {
                fileTree(dir: it, exclude: [
                        '**/Main.class',
                        '**/Application.class'
                ])
            })
    )
    violationRules {
        rule {
            limit {
                minimum = 0.80
            }
        }
    }
}

check {
    dependsOn jacocoTestCoverageVerification
}